version: "3.9"
services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-} # local, docker, docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

#  fatura-services:
#    container_name: fatura-services
#    image: sirondba/fatura-services:latest
##    image: fatura-services:latest
##    build: #Para criar a a imagem docker localmente comentar a linha 21 e descomentar as linhas 22, 23, 24 e 24
##      context: .
##      dockerfile: ./Dockerfile
#    networks:
#      - automacao-net
#    ports:
#      - "8081:8080"
#    environment:
#      - DATABASE_URL=jdbc:postgresql://db-automacao-fatura:5432/db_automacao-fatura
#      - PORT=8080


networks:
  automacao-net:
    external:
      name: automacao-resgate-fatura_automacao-net