server:
  port: ${PORT:9080}

spring:
  application:
    name: accountTransfer
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      read_unknown_enum_values_as_null: true
    serialization:
      write_dates_as_timestamps: false
  cloud:
    config:
      enabled: false

api:
  client:
    url: http://localhost:9090/clientes
  account:
    url: http://localhost:9090/contas
  bacen:
    notificacao:
      url: http://localhost:9090/notificacoes

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:test}
      secret-key: ${AWS_SECRET_KEY:test}
    region:
      static: ${AWS_REGION:us-east-1}
    endpoint:
      uri: http://localhost:4566
    s3:
      endpoint: http://s3.localhost.localstack.cloud:4566/

events:
  topic: sns-transaction
  queue: notification-queue

cache:
  redis:
    config:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
    caches[0]:
      cacheName: account-transfer:dadosClientePorCodigo
      expiration: ${CACHE_DURATION_DADOS_PESSOA:PT30S}
    caches[1]:
      cacheName: account-transfer:dadosContaPorCodigo
      expiration: ${CACHE_DURATION_DADOS_CONTA:PT1H}
#    caches[2]:
#      cacheName: account-transfer:dadosContaPorSaldo
#      expiration: ${CACHE_DURATION_DADOS_CONTA:PT1H}