server:
  port: ${PORT:8080}

spring:
  application:
    name: accountTransfer
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write_dates_as_timestamps: false

api:
  client:
    url: http://localhost:9090/clientes
  account:
    url: http://localhost:9090/contas
  bacen:
    notificacao:
      url: http://localhost:9090/notificacoes

cache:
  redis:
    config:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
    caches[0]:
      cacheName: account-transfer:dadosClientePorCodigo
      expiration: ${CACHE_DURATION_DADOS_PESSOA:PT30S}
    caches[1]:
      cacheName: account-transfer:dadosContaPorCodigo
      expiration: ${CACHE_DURATION_DADOS_CONTA:PT1H}
#    caches[2]:
#      cacheName: account-transfer:dadosContaPorSaldo
#      expiration: ${CACHE_DURATION_DADOS_CONTA:PT1H}